version: '3.7'

services:

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "12000mb", "--maxmemory-policy", "allkeys-lru"]
    hostname: redis
    volumes:
     - ../redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['celery', '-A', 'app.app', 'worker', '--loglevel', 'INFO', '--pool', 'eventlet', '--concurrency', '3', '-n', 'worker@%h']
    environment:
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - S3_KEY=$S3_KEY
    depends_on:
      - redis
    volumes:
     - ../shared:/shared

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python', 'backend.py']
    environment:
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - S3_KEY=$S3_KEY
    expose:
      - 5556
    volumes:
     - ../shared:/shared

  flower:
    restart: always
    image: mher/flower:2.0
    container_name: celery-flower
    command: celery flower -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    ports:
      - 5555:5555

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flower
